import { Router } from "express";
import { z } from "zod";

import { listTemplates, getTemplateById as getTemplateMeta } from "../templates/templateService.js";
import { requireAuth } from "../middleware/auth.js";
import { adminOnly } from "../middleware/admin.js";
import { prisma } from "../db/prisma.js";

export const templateRouter = Router();

templateRouter.get("/", async (req, res) => {
  const { language, level } = req.query;
  const templates = await listTemplates({
    language: typeof language === "string" ? language : undefined,
    level: typeof level === "string" ? level : undefined,
  });
  res.json({ templates });
});

templateRouter.get("/:id", async (req, res) => {
  const id = req.params.id;
  const template = await getTemplateMeta(id);
  if (!template) return res.status(404).json({ error: "Template not found" });
  res.json({ template });
});

const createTemplateSchema = z.object({
  language: z.string().min(2),
  level: z.enum(["beginner", "intermediate", "advanced"]),
  scenario: z.string().min(2),
  startingPrompt: z.string().min(1),
});

const updateTemplateSchema = z.object({
  language: z.string().min(2),
  level: z.enum(["beginner", "intermediate", "advanced"]),
  scenario: z.string().min(2),
  startingPrompt: z.string().min(1),
});

// Admin: create or update a template
templateRouter.post("/", requireAuth, adminOnly, async (req, res) => {
  const payload = createTemplateSchema.parse(req.body);
  const created = await prisma.template.create({
    data: {
      // id is auto-generated by Prisma client if default(cuid()) is set; otherwise Prisma client will create one.
      language: payload.language,
      level: payload.level,
      scenario: payload.scenario,
      summary: payload.scenario, // summary not required; reuse scenario
      data: {
        startingPrompt: payload.startingPrompt,
      },
    },
  });
  const meta = await getTemplateMeta(created.id);
  res.status(201).json({ template: meta });
});

templateRouter.put("/:id", requireAuth, adminOnly, async (req, res) => {
  const id = req.params.id;
  const payload = updateTemplateSchema.parse(req.body);
  const existing = await prisma.template.findUnique({ where: { id } });
  if (!existing) return res.status(404).json({ error: "Template not found" });
  const updated = await prisma.template.update({
    where: { id },
    data: {
      language: payload.language,
      level: payload.level,
      scenario: payload.scenario,
      summary: payload.scenario,
      data: {
        startingPrompt: payload.startingPrompt,
      },
    },
  });
  const meta = await getTemplateMeta(updated.id);
  res.json({ template: meta });
});
